### ISSUE TITLE
Crash when placing crate at Y = 1

### ISSUE THREAD

**Issue by copygirl** [copygirl/BetterStorage#295]
```
java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:511)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:842)
    at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
    at net.mcft.copy.betterstorage.utils.WorldUtils.get(WorldUtils.java:109)
    at net.mcft.copy.betterstorage.tile.crate.TileCrate$ConnectedTextureCrate.canConnect(TileCrate.java:87)
    at net.mcft.copy.betterstorage.misc.ConnectedTexture.getConnectedIcon(ConnectedTexture.java:43)
    at net.mcft.copy.betterstorage.tile.crate.TileCrate.func_149673_e(TileCrate.java:52)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
    [...]
```

Probably also an issue on Y = 0 and maybe near the world height limit.
Just putting this on the issue tracker for reasons, probably won't fix it though.

**Comment by Ganjalf-Amsterdoom** [comment]
plz fix q^c^p
