### ISSUE TITLE
[CRASH] BCA and Better Storage caused a crash at SSP

### ISSUE THREAD

**Issue by hron84** [copygirl/BetterStorage#314]
**Note:** This is a cross-mod issue, see [the other issue too](https://github.com/BCA-Team/Buildcraft-Additions/issues/460)

I used Semi-Automatic Duster from BuildCraft Additions (S-AD) and BetterStorage crates to work together because S-AD can output dusts automatically to a storage and I thought a crate would be a good target for this. Everything worked fine, but after dusting a tenth or twelweth (somewhat this amount) ore block I got this crash:

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2015.12.27. 0:31
Description: Ticking entity

java.lang.IllegalStateException: Can't be called client-side.
	at net.mcft.copy.betterstorage.tile.crate.TileEntityCrate.getPileData(TileEntityCrate.java:46)
	at net.mcft.copy.betterstorage.tile.crate.TileEntityCrate.func_70301_a(TileEntityCrate.java:286)
	at buildcraftAdditions.utils.Utils.outputStack(Utils.java:265)
	at buildcraftAdditions.tileEntities.Bases.TileDusterWithConfigurableOutput.dust(TileDusterWithConfigurableOutput.java:103)
	at buildcraftAdditions.tileEntities.TileSemiAutomaticDuster.makeProgress(TileSemiAutomaticDuster.java:32)
	at buildcraftAdditions.blocks.BlockSemiAutomaticDuster.func_149746_a(BlockSemiAutomaticDuster.java:38)
	at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:179)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:738)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(Unknown Source)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full log is available [here](https://gist.github.com/hron84/2ad15ffa8144ed4ca49f)

Affected versions: 

Forge 10.13.4.1566
BuildCraft: 7.1.14
BuildCraft-Additions: 2.2.3
Better Storage: 0.13.1.126

If it is possible, please take look into this and let me know what did I wrong or what more information should be provided for fix the bug.

Thanks for your work.

**Comment by copygirl** [comment]
Most likely a fault on BCA's side. Inventories should not be accessed client-side. Their contents are only available on the server anyway. Looks like BCA is running code on both sides that should only run on the server.

Closing the issue for now.
Thanks for letting us know.

**Comment by hron84** [comment]
@copygirl Thanks for your great assistance on this issue.
